### ISSUE TITLE
Stop working on your chutiya player

### ISSUE THREAD

**Issue by sbyeniden** [OoLunar/Music_Player#5]
Your *chutiya* player is exactly *chutiya* like you. FUCK YOU TCD VETERAN I DON'T SEE YOU BYE NEVER TOUCH YENIDEN YOU FUCKING NIGGER RETARDED SHUT THE FACK UP!

**Comment by OoLunar** [comment]
Ah yes, just what I wanted to wake up too.

First off, your insults are just as worthless as you are. They're empty and bland. Instead of writing pointless insults, why don't you tell me what you disliked about it?

I'm fully aware that the music player is buggy and incomplete, which is why it's on GitHub instead of Google Play Store. I'm not sure what you were expecting, but maybe you should lower your expectations so you don't look like the inconsiderate douchebag that you are deep down.

Also, in what way is TCD related to this? Calling me a TCD Veteran makes me sound like someone who's gotten respect from the community. You aren't trying to complement me, are you? I'm beginning to wonder if you know how insults work...

**Comment by sbyeniden** [comment]
> First off, your insults are just as worthless as you are.

No you, madarfakar bladi beech cant yeetar gay pussi fakar.

> They're empty and bland.

You exactly know what's bad about it, so I don't need to point it out. But okay, since you're so blind and hold a large ego to find out here's an example:
https://github.com/OoLunar/Music_Player/blob/980c4bd016d758d078af75e13cf0160661a48c8a/src/main.rs#L42-L50

I hope I don't need to further explain the thing bad with this.


> Calling me a TCD Veteran makes me sound like someone who's gotten respect from the community.

I believe calling someone a *TCD Veteran* is more insulting than *nigger, faggot, jew*. But whatever, since you have a *TCD Veteran brain* you couldn't comprehend it as an insult. Don't worry, it's normal.

**Comment by OoLunar** [comment]
>     First off, your insults are just as worthless as you are.
> No you, madarfakar bladi beech cant yeetar gay pussi fakar.

LOL. That was pretty good.

> You exactly know what's bad about it, so I don't need to point it out. But okay, since you're so blind and hold a large ego to find out here's an example:

I see nothing wrong with it. It iterates the list of music files, prints out in console what song it's about to play, then plays it. The only thing I could see "bad" about it is how it's somewhat unreadable. However, even though I haven't touched Rust in 5 months, I was still able to read it just fine. If it's so awful, why don't you give me a better code snippet?

> I believe calling someone a TCD Veteran is more insulting than nigger, faggot, jew. But whatever, since you have a TCD Veteran brain you couldn't comprehend it as an insult. Don't worry, it's normal.

So you *do* have something against TCD. What happened, where you banned?

**Comment by sbyeniden** [comment]
> I see nothing wrong with it.

Oh fuck man, you don't even realize from insults? Well it seems you don't. Okay so, you could just a for-loop at here (or atleast `for_each`), why are you using `.map()` here and then `.collect()`ing? THIS IS ABSOLUTELY WORTHLESS HERE AS YOU DO NOTHING WITH THE OUTPUT!

Even a noob JavaScript coder knows this but not you.

**Comment by OoLunar** [comment]
> Even a noob JavaScript coder knows this but not you.

Let's be real here. Most Javascript programmers won't give two thoughts about memory allocations.

>  Okay so, you could just a for-loop at here (or atleast for_each), why are you using .map() here and then .collect()ing?

Seeing as how I still despise using maps, that's likely what I tried doing first. `.map()` is likely the only solution I came across.

> THIS. DOES. TEMPORARY. HEAP. ALLOCATION. WHICH. DEGRADES. THE. PERFORMANCE. OF. YOUR. FUCKING. PROGRAM.

If you're expecting perfect code, go look at Google. I am a person who's looking for functionality, not performance. In reality, this only allocates what, an extra kilobyte? In today's society, that's nothing. Obviously if I can improve on performance, without risking readability, I will.

Finally, why are you using caps and cursing at me? It makes me think you're mad, despite this being a conversation that's lasted for two days now. That's one hell of a grudge for 8 lines of code.

**Comment by OoLunar** [comment]
Look, if it really matters to you that much, 1 of 2 things can happen

- You submit a PR with code that you're content with.

- You deal with it and I'll fix it when I can.

**Comment by sbyeniden** [comment]
> - You submit a PR with code that you're content with.

I ain't your slave.

> If you're expecting perfect code, go look at Google. I am a person who's looking for functionality, not performance.

Why are you always pointing me towards Google? And, why shouldn't you look upon performance and most importantly code-reliability (a key component in open source dev).

> In reality, this only allocates what, an extra kilobyte? In today's society, that's nothing.

Now with this negligence, you could never design good software ever. What makes you think it's okay in this case where it could be completely eliminated?

> That's one hell of a grudge for 8 lines of code.

I said, `here's an example` which doesn't mean that it is the only thing bad, are you so dumb to understand this? What do you expect me to? Spoonfeed you? I assume, you're not a 8 year old for that.

**Comment by OoLunar** [comment]
Here's my point of view:

You come in, telling me my project is shit. I told you that it's on here so I can learn, not so it can be used in production. You continue insulting the project, this time pointing out code. I tell you that you're welcome to fix it if you're discontent with it. You fire back that "you're not my slave." I never claimed you were, nor was I forcing you to do anything. Yet here you are with the audacity to act like my boss, telling me what's wrong with everything, without providing me a solution. No, I don't expect to be spoonfed. I never have, and I never will. However part of "constructive criticism" is telling the user what went wrong, and how it could've gone instead. As far as I'm concerned, you're here because you can't get over the fact that some drama went down between you and TCD, and you can't get over it. So now here you are attacking well known members of TCD because of how much of a piss poor attitude you have. This is no longer relavent to the music player. Take you and your microptimizations somewhere helpful, like SpaceX, instead of going after nobodies like me.

**Comment by sbyeniden** [comment]
> As far as I'm concerned, you're here because you can't get over the fact that some drama went down between you and TCD, and you can't get over it.

TCD is a extremely retarded place, where retards like you reside. And your **praised** (asslicked) mods kick people when they don't agree with mods' opinion. I am quite shocked that people are still there. Y'all just talk like humanoids, no feelings, no humor, nothing.

> So now here you are attacking well known members of TCD because of how much of a piss poor attitude you have.

Who gives a fuck if you're a *well-known* TCD member? Afterall, you're a TCD veteran aka. *big big chutiya*. Because being it is nothing but amplifying your chances for being jobless for rest of your life.

> You come in, telling me my project is shit.

Because it is and I have the freedom to state it.

> I told you that it's on here so I can learn, not so it can be used in production.

So why don't you learn the way to do this all properly?

> Yet here you are with the audacity to act like my boss, telling me what's wrong with everything, without providing me a solution.

Infact, I *have* given you a solution *to use a for-loop to iterate over `music_files`*. Probably because of your universe brain you overlooked it, smh. I'm starting to suspect that you have austism.

> No, I don't expect to be spoonfed. I never have, and I never will.

I already gave you the solution, do you want me to write the full code for you? What do I look like to you? Chutiya?

> Take you and your microptimizations somewhere helpful, like SpaceX, instead of going after nobodies like me.

How's that a microoptimization to you? It is a quite significant optimization. Also why the fuck are you pointing me towards big companies? They already have good engineers *like me* to do stuff properly, unlike you.

**Comment by OoLunar** [comment]
Quit wasting my time.
